libmarkdown.a:
    stage: build
    image: quay.io/craigbarnes/lua-testing
    artifacts:
        paths:
            - build/discount-2.2.1/libmarkdown.a
            - build/discount-2.2.1/mkdio.h
    cache:
        paths:
            - build/discount-2.2.1.tar.gz
    script:
        - make -j`nproc` local-discount

tests:
    stage: test
    image: quay.io/craigbarnes/lua-testing
    script:
        - make clean-obj all print-lua-v check USE_LOCAL_DISCOUNT=1
        - make clean-obj all print-lua-v check LUA_PC=lua53 USE_LOCAL_DISCOUNT=1
        - make clean-obj all print-lua-v check LUA_PC=lua52 USE_LOCAL_DISCOUNT=1
        - make clean-obj all print-lua-v check LUA_PC=lua51 USE_LOCAL_DISCOUNT=1
        - make clean-obj all print-lua-v check LUA_PC=luajit USE_LOCAL_DISCOUNT=1

pages:
    image: quay.io/craigbarnes/pandoc
    artifacts: {paths: [public]}
    only: [master]
    script:
        - git fetch --tags
        - make -j`nproc` dist check-dist
