tests:
    image: quay.io/craigbarnes/lua-testing
    before_script:
        - make -j`nproc` local-discount
    script:
        - make clean-obj all print-lua-v check
        - make clean-obj all print-lua-v check LUA_PC=lua53
        - make clean-obj all print-lua-v check LUA_PC=lua52
        - make clean-obj all print-lua-v check LUA_PC=lua51
        - make clean-obj all print-lua-v check LUA_PC=luajit

pages:
    image: quay.io/craigbarnes/pandoc
    artifacts: {paths: [public]}
    only: [master]
    script:
        - git fetch --tags
        - make -j`nproc` dist check-dist
