tests:
    stage: test
    image: quay.io/craigbarnes/lua-testing
    script:
        - make check-discount-tarball
        - make -j`nproc` local-discount
        - make clean-obj all print-lua-v check USE_LOCAL_DISCOUNT=1
        - make clean-obj all print-lua-v check LUA_PC=lua53 USE_LOCAL_DISCOUNT=1
        - make clean-obj all print-lua-v check LUA_PC=lua52 USE_LOCAL_DISCOUNT=1
        - make clean-obj all print-lua-v check LUA_PC=lua51 USE_LOCAL_DISCOUNT=1
        - make clean-obj all print-lua-v check LUA_PC=luajit USE_LOCAL_DISCOUNT=1
        - rm -rf build
        - make clean
        - make check-luarocks-make LUAROCKS=luarocks-5.3

pages:
    stage: deploy
    image: quay.io/craigbarnes/pandoc
    artifacts: {paths: [public]}
    only: [master]
    script:
        - git fetch --tags
        - make -j`nproc` dist check-dist
